## Aerobic systems

When oxygen is available energy is in abundance. A mole of glucose can result in more than 20 mols of ATP (depending on the $P/O$ ratios) through respiration, while the standard anaerobic catabolism of lactic acid and ethanol formation only gives one 2 moles of ATP per mole of glucose. During respiration the carbon backbone of glucose is destroyed since the only $CO_2$ and $H_2O$ forms. This stands in contrast with anaerobic systems where sections of the carbon backbone is excreted from the cell and regularly used as commercial chemicals (ethanol, lactic acid, succinic acid, acetic acid etc.). For some aerobic processes biomass itself is the product like the _Saccharomyces cerevisiae_ example of [tutorial 3.2](https://nbviewer.jupyter.org/github/willienicol/Biochemical-engineering-notes/blob/master/Tutorials/Tut%203.2.ipynb). But apart from making biomass, is it possible to make other molecules when the catabolism only results in the formation of $CO_2$ and $H_2O$?

The answer is a definite yes. Most commercial fermentation processes employ aerobes where oxygen is sparged through the bioreactor. In all of these systems a major part of the carbon flux is directed to molecules with a carbon skeleton. Examples of these include organic acids like citric, fumaric and malic acid, alcohols like propane diol, amino acids like glutamate and lysine, proteins like insulin and cellulase and various other commercial chemicals. These biochemicals cannot be seen as ‘true’ catabolites, since their production is typically not associated with ATP production. We will however consider the metabolic pathways for producing these chemicals as part of the catabolism that we model. Some reactions might require ATP and will be directly considered in the ATP balance. For these scenarios respiration will fuel the ATP requirements of the anabolism and the energy hungry catabolic reactions. The principles of metabolic flux modelling discussed in [section 4.2](https://nbviewer.jupyter.org/github/willienicol/Biochemical-engineering-notes/blob/master/4%20Stoichiometry%20that%20includes%20internal%20reactions/Main%20fermentative%20pathways.ipynb) will apply directly. 

But why does these molecules get produced if ATP generation is not the objective. The answer to this question lies in the organism’s interaction with its environment and fellow competitors. In most scenarios the excreted product performs an extracellular function that favours the survival of the organism. For example, extracellular fungal enzymes or exoenzymes are used to break complex macromolecules like cellulose into digestible glucose units. The enzymes are thus used to prepare the food to the organism on the outside. Another example is the excretion of organic acids by some fungi. This creates a low pH environment that the organism is more adapted to and hence it has a growth advantage over other competing organisms.

Whatever the metabolism of these organism entail, oxygen is used to generate ATP in an efficient manner. It also ‘digest’ excess NADH formed in some of these processes. In order to model the metabolic flux distributions of these systems, oxidative phosphorylation need to be included into the flux model. This can be done by defining a molar oxygen rate within the flux model:

<img src="OP1.png" width="400" />

This is merely the representation of the equation we had in [chapter 2](https://nbviewer.jupyter.org/github/willienicol/Biochemical-engineering-notes/blob/master/2%20Basic%20biochemistry/Basic%20Biochemistry.ipynb):

$$2NADH+O_2→2(P⁄O)_{NADH} ATP+2H_2 O$$

We will now return to the _Saccharomyces cerevisiae_ example ([tutorial 3.2](https://nbviewer.jupyter.org/github/willienicol/Biochemical-engineering-notes/blob/master/Tutorials/Tut%203.2.ipynb)) where biomass production is considered. The full TCA model will be performed for this example. After the example it will be shown that respiration can be reduced to a much simpler flux model. The reason for the detail modelling of the TCA cycle is to provide a tool for handling scenarios where TCA intermediates (or metabolites a few enzymatic steps away from a TCA intermediate) are considered as excretion products. Numerous commercial fermentation products originates from TCA cycle intermediates.

The cmol flux diagram of are given by the following:

<img src="TCA.png" width="800" />

***Flux model of the TCA cycle in conjunction with cell growth*** *Glu - glucose, X - biomass, Pyr - pyruvate, AcCoA - acetyl-CoA, Cit  -citrate, $\alpha$-Ket - $\alpha$-ketoglutarate, Su-CoA - succinyl-CoA, OXA - oxaloacetate*

Take note of the following:
* Blue nodes giving stoichiometric nodes
* All rates have units of $\frac{\text{cmol/mol i}}{\text{cmol X}\cdot\text{h}}$
* Pyruvate oxidation occurs via pyruvate dehydrogenase (PDH)
* $r_6$ represents a four carbon molecule joining up with a two carbon molecule ($r_3$) to result in a six carbon molecule ($r_4$) and thus equation 4.
*  Equation 5a substituted into equation 5b results in equation 4. Accordingly either 5a or 5b should be specified to have a linear independent set of equations.
*	The transition in the cycle from $C_6$ to $C_5$ to $C_4$, where carbon is lost via $CO_2$ formation. The last stoichiometric balances reflect these transitions.
*	The $\frac{1}{2}$ NADH on $v_6$ is two separate oxidation steps ($2\times\frac{1}{4}$) in the cycle where FADH is considered as NADH.
*	The GTP formed in the cycle is considered as ATP.
*	Oxidative phosphorylation is reflected in the ATP and NADH balance by using the oxygen flux as reference. The $(P/O)$ is specified as 1.5.
*   The growth rate ($\mu$) as basis specification. 

The flux model does not solve for the total $CO_2$ produced. We can include an additional rate ($r_{CO_2}$) and an additional equation to address the issue. The equation will be as follow:

$$r_{CO_2}=r_8=\alpha r_1+\frac{1}{2}r_3+\frac{1}{5}r_5+\frac{1}{4}r_6$$

Given 9 equations for 9 rates ($CO_2$ included) the system is fully specified. The formulation can easily be solved by the matrix method. Like before we'll choose $\alpha=0.1 \frac{\text{mol}\,CO_2}{\text{cmol X}}$ and work out $\beta=0.1\frac{\text{mol NADH}}{\text{cmol X}}$ given that biomass is given as $CH_{1.8}O_{0.5}N_{0.2}$. We'll further define $\gamma=2.5\frac{\text{mol ATP}}{\text{cmol X}}$, $\theta=0.1 \frac{\text{mol ATP}}{\text{mol X}\cdot \text{h}}$ and $\mu =0.25 \frac{1}{\text{h}}$. Since this is a big matrix let's opt for Excel to define the define the stoichiometric matrix. It is much easier when columns are clearly defined: 


The stoichiometric matrix in Excel will look like this:

<img src="TCA_excel.png" width="700" />

We can easily solve for the formulation in Excel. [This video will show you how](https://www.youtube.com/watch?v=vLsouen-G8M)

Alternatively, we can import the Excel formulation into Python. Note that the **pandas** tool will import from the first sheet in the specified Excel file.

In [39]:
import pandas, numpy
pandas.read_excel('TCA_example.xlsx')

0    1         2    3         4    5     6  7  8
0 -1  1.1  1.000000  0.0  0.000000  0.0  0.00  0  0
1  0  0.0  0.000000  1.0 -1.000000  0.0  1.00  0  0
2  0  0.0 -0.666667  1.0  0.000000  0.0  0.00  0  0
3  0  0.0  0.000000  0.0 -0.666667  0.0  1.00  0  0
4  0  0.0  0.000000  0.0 -0.833333  1.0  0.00  0  0
5  0  0.1  0.333333  0.5  0.000000  0.2  0.75 -2  0
6  0 -2.5  0.333333  0.0  0.000000  0.0  0.25  3  0
7  0  1.0  0.000000  0.0  0.000000  0.0  0.00  0  0
8  0  0.1  0.000000  0.5  0.000000  0.2  0.25  0 -1

It is possible to define a matrix in Python from the Excel file. Note that the first row and column defined in Excel (in colour peach) will not form part of the imported matrix. Let's import and solve the formulation:

In [40]:
M = numpy.matrix(pandas.read_excel('TCA_example.xlsx'))
mu,theta=0.25,0.1
C = numpy.matrix([[0,0,0,0,0,0,theta,mu,0]]).T
r = numpy.linalg.solve(M,C)
r   


matrix([[ 0.4625],
        [ 0.25  ],
        [ 0.1875],
        [ 0.125 ],
        [ 0.375 ],
        [ 0.3125],
        [ 0.25  ],
        [ 0.2   ],
        [ 0.2125]])

Let's immediately check for mass balance consistency by performing the overall balance of tutorial 3.2. Note the inclusion of $NH_3$ and the oxygen rate specification from the previous answer. 

In [42]:
rO2=r[7,0].tolist()  #oxygen rate
S = numpy.matrix([[-1,0,0,1,1,0],
                  [-2,-3,0,1.8,0,2],
                  [-1,0,-2,0.5,2,1],
                  [0,-1,0,0.2,0,0],
                  [0,0,0,1,0,0],
                  [0,0,1,0,0,0]])
        
C2 = numpy.matrix([[0,0,0,0,mu,rO2]]).T
r2 = numpy.linalg.solve(S,C2)
r2      

matrix([[ 0.4625],
        [ 0.05  ],
        [ 0.2   ],
        [ 0.25  ],
        [ 0.2125],
        [ 0.3125]])

The uptake and excretion rates are exactly the same. **Make sure you agree with this statement!** We have taken a long route to include the additional equation given by the ATP balance. This is why one specification was required when solving for the elemental balances. See the following video for an alternative view of what the previous calculation was about:

[Video: Lecture 8 Extra equations](https://youtu.be/OdbcdI1lUhI)


### Simplification of respiration

The full TCA model is useful since the steady state internal rates (not excreted) are quantified. When TCA cycle intermediates are excreted the full TCA cycle model needs to be used. However, if the sole purpose of the TCA cycle is to provide NADH for oxidative phosphorylation, the flux model can be significantly reduced. The following simplified model should give the same as the model above:

<img src="TCA2.png" width="650" />

Note that the $\frac{2}{3}$ATP in the respiration flux ($r_2$) is $\frac{2}{3}$ATP from glycolysis and $\frac{2}{3}$ATP from pyruvate oxidation via pyruvate dehydrogenase. The $(P/O)$ value remains at 1.5.

Let’s confirm if we get the same answer:


In [43]:
alpha=0.1
beta=0.1   # Can be calculated - see section 4.1
gamma=2.5
mu,theta = 0.25, 0.1

S = numpy.matrix([[-1,(1+alpha),1,0],
[0,beta,2,-2],
[0,-gamma, 2/3,3],                  
[0,1,0,0]])
        
C = numpy.matrix([[0,0,theta,mu]]).T
Y = numpy.linalg.solve(S,C)
Y      

matrix([[ 0.4625],
        [ 0.25  ],
        [ 0.1875],
        [ 0.2   ]])

Exactly the same. Definitely the simplest solution to aerobic growth of _S. cerevisiae_. 

<img src="simplify.jpg" width="450" />

[Back to Contents page](https://nbviewer.jupyter.org/github/willienicol/Biochemical-engineering-notes/blob/master/List%20of%20contents.ipynb)
